// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh_g0bbOlAPGKd6Q_q3jHf7WIh9WBPx1M',
    appId: '1:464084313906:web:0de43d6c4fd712b1da992b',
    messagingSenderId: '464084313906',
    projectId: 'aqarat-eaa2e',
    authDomain: 'aqarat-eaa2e.firebaseapp.com',
    storageBucket: 'aqarat-eaa2e.firebasestorage.app',
    measurementId: 'G-BMGPWTLGR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtAOeWlzDRfKqW5UieEtTD28GR4cXDwzU',
    appId: '1:464084313906:android:c8dcb538d4479eb6da992b',
    messagingSenderId: '464084313906',
    projectId: 'aqarat-eaa2e',
    storageBucket: 'aqarat-eaa2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcIg_TTOYtxW1K0tnjsWaLVSfUuycU6i4',
    appId: '1:464084313906:ios:baf84c80e2c692cbda992b',
    messagingSenderId: '464084313906',
    projectId: 'aqarat-eaa2e',
    storageBucket: 'aqarat-eaa2e.firebasestorage.app',
    iosBundleId: 'com.example.aqaratApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcIg_TTOYtxW1K0tnjsWaLVSfUuycU6i4',
    appId: '1:464084313906:ios:baf84c80e2c692cbda992b',
    messagingSenderId: '464084313906',
    projectId: 'aqarat-eaa2e',
    storageBucket: 'aqarat-eaa2e.firebasestorage.app',
    iosBundleId: 'com.example.aqaratApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh_g0bbOlAPGKd6Q_q3jHf7WIh9WBPx1M',
    appId: '1:464084313906:web:c637de0e0daf3c14da992b',
    messagingSenderId: '464084313906',
    projectId: 'aqarat-eaa2e',
    authDomain: 'aqarat-eaa2e.firebaseapp.com',
    storageBucket: 'aqarat-eaa2e.firebasestorage.app',
    measurementId: 'G-GBG912EKTY',
  );
}
